version: '3'

services:
  # Python Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Mount your code directory into the container
    depends_on:
      - db  # Make sure the database container is started first

  # PostgreSQL Service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    # Optionally, you can include initialization scripts by mounting a volume:
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
